// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qrgbkgcrpmdpjvgkeqke.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFyZ2JrZ2NycG1kcGp2Z2tlcWtlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg3MzgwMjMsImV4cCI6MjA2NDMxNDAyM30.nN3g1k_sKT2KpFNBTkppkvtZJivR8-VzHQxl-bZVk1s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);